import { GENDER_TYPE, MEMBER_TYPES, USER_STATUS } from "./enum";
import {
  STATSCARDDATA,
  STATSCARDPROPS,
  TEAM_LIST_DATA_PROPS,
  TEAM_LIST_HEADER,
} from "./type";
import {
  Groups,
  PersonOff,
  Lightbulb,
  Science,
  Apartment,
  Hail,
  FileCopyOutlined,
  RocketLaunch,
  MonetizationOn,
  MoneyOff,
  BusinessCenter,
} from "@mui/icons-material";

export const STUDENT_SIDEBAR_DATA = [
  {
    label: "Dashboard",
    url: "/dashboard/student",
  },
  {
    label: "Innovation Management",
    url: "/dashboard/student/innovation-management",
  },
  {
    label: "Startup Management",
    url: "/dashboard/student/startup-management",
  },
  {
    label: "Resource Access",
    url: "/dashboard/student/resource-access",
  },
  {
    label: "Membership Management",
    url: "/dashboard/student/membership-management",
  },
];
export const EDUCATOR_SIDEBAR_DATA = [
  {
    label: "Dashboard",
    url: "/dashboard/educator",
  },
  {
    label: "Student Management",
    url: "/dashboard/educator/student-management",
  },
  {
    label: "Innovation Approval",
    url: "/dashboard/educator/innovation-approval",
  },
  {
    label: "Research Submission",
    url: "/dashboard/educator/research-submission",
  },
  {
    label: "Resource Access",
    url: "/dashboard/educator/resource-access",
  },
];

export const INSTITUTION_SIDEBAR_DATA = [
  {
    label: "Dashboard",
    url: "/dashboard/institution",
  },
  {
    label: "Educator Management",
    url: "/dashboard/institution/educator-management",
  },
  {
    label: "Student Management",
    url: "/dashboard/institution/student-management",
  },
  {
    label: "Team Management",
    url: "/dashboard/institution/team-management",
  },
  {
    label: "Innovation Submission",
    url: "/dashboard/institution/innovation-submission",
  },
  {
    label: "Research Submission",
    url: "/dashboard/institution/research-submission",
  },

  {
    label: "Startup Submission Management",
    url: "/dashboard/institution/startup-management",
  },
  {
    label: "Resource Access",
    url: "/dashboard/institution/resource-access",
    subItems: [
      {
        label: "Playbooks",
        url: "/dashboard/institution/resource-access/playbooks",
      },
      {
        label: "Modules",
        url: "/dashboard/institution/resource-access/modules",
      },
      {
        label: "Templates",
        url: "/dashboard/institution/resource-access/templates",
      },
    ],
  },
];

export const TEACHER_DATA = [
  {
    id: "E-001",
    name: "Dr. Rajesh Kumar",
    email: "rajesh@edu.in",
    phone: "9876543210",
    subject: "Mathematics",
    status: "Member",
    membershipId: "AI-M-001",
    gender: GENDER_TYPE.MALE,
  },
  {
    id: "E-002",
    name: "Priya Sharma",
    email: "priya@edu.in",
    phone: "9876543211",
    subject: "Physics",
    status: "Not a member",
    membershipId: "-",
    gender: GENDER_TYPE.FEMALE,
  },
  {
    id: "E-003",
    name: "Ankit Verma",
    email: "ankit@edu.in",
    phone: "9876543212",
    subject: "Chemistry",
    status: "Member",
    membershipId: "AI-M-003",
    gender: GENDER_TYPE.MALE,
  },
  {
    id: "E-004",
    name: "Sunita Rao",
    email: "sunita@edu.in",
    phone: "9876543213",
    subject: "Biology",
    status: "Not a member",
    membershipId: "-",
    gender: GENDER_TYPE.FEMALE,
  },
  {
    id: "E-005",
    name: "Vikram Singh",
    email: "vikram@edu.in",
    phone: "9876543214",
    subject: "Computer Science",
    status: "Member",
    membershipId: "AI-M-006",
    gender: GENDER_TYPE.MALE,
  },
  {
    id: "E-006",
    name: "Meera Iyer",
    email: "meera@edu.in",
    phone: "9876543215",
    subject: "History",
    status: "Member",
    membershipId: "AI-M-007",
    gender: GENDER_TYPE.FEMALE,
  },
  {
    id: "E-007",
    name: "Rohan Das",
    email: "rohan@edu.in",
    phone: "9876543216",
    subject: "Geography",
    status: "Member",
    membershipId: "AI-M-008",
    gender: GENDER_TYPE.MALE,
  },
  {
    id: "E-008",
    name: "Sneha Gupta",
    email: "sneha@edu.in",
    phone: "9876543217",
    subject: "English",
    status: "Member",
    membershipId: "AI-M-009",
    gender: GENDER_TYPE.FEMALE,
  },
  {
    id: "E-009",
    name: "Amit Patel",
    email: "amit@edu.in",
    phone: "9876543218",
    subject: "Economics",
    status: "Member",
    membershipId: "AI-M-010",
    gender: GENDER_TYPE.MALE,
  },
  {
    id: "E-010",
    name: "Kavita Reddy",
    email: "kavita@edu.in",
    phone: "9876543219",
    subject: "Political Science",
    status: "Member",
    membershipId: "AI-M-011",
    gender: GENDER_TYPE.PREFER_NOT_TO_SAY,
  },
  {
    id: "E-011",
    name: "Sanjay Joshi",
    email: "sanjay@edu.in",
    phone: "9876543220",
    subject: "Physical Education",
    status: "Member",
    membershipId: "AI-M-012",
    gender: GENDER_TYPE.MALE,
  },
];

export const STUDENT_HEADER_DATA = [
  "Id",
  "Name",
  // "Email",
  "Phone",
  "Grade",
  "Gender",
  "Status",
  "Membership Id",
  "Actions",
];

export const STUDENT_TABLE_DATA = [
  {
    id: "S-01",
    name: "Kunal Sharma",
    email: "kunal.sharma@digixito.com",
    phone: "9354678205",
    grade: "12th",
    membershipId: "M-01",
    status: "Member",
    gender: GENDER_TYPE.MALE,
  },
  {
    id: "S-02",
    name: "Kunal Sharma",
    email: "kunal.sharma@digixito.com",
    phone: "9354678205",
    grade: "12th",
    membershipId: "-",
    status: "Not a member",
    gender: GENDER_TYPE.MALE,
  },
  {
    id: "S-03",
    name: "Kunal Sharma",
    email: "kunal.sharma@digixito.com",
    phone: "9354678205",
    grade: "12th",
    membershipId: "M-03",
    status: "Member",
    gender: GENDER_TYPE.FEMALE,
  },
  {
    id: "S-04",
    name: "Kunal Sharma",
    email: "kunal.sharma@digixito.com",
    phone: "9354678205",
    grade: "12th",
    membershipId: "-",
    status: "Not a member",
    gender: GENDER_TYPE.FEMALE,
  },
  {
    id: "S-05",
    name: "Kunal Sharma",
    email: "kunal.sharma@digixito.com",
    phone: "9354678205",
    grade: "12th",
    membershipId: "M-05",
    status: "Member",
    gender: GENDER_TYPE.PREFER_NOT_TO_SAY,
  },
  {
    id: "S-06",
    name: "Kunal Sharma",
    email: "kunal.sharma@digixito.com",
    phone: "9354678205",
    grade: "12th",
    membershipId: "M-06",
    status: "Member",
    gender: GENDER_TYPE.MALE,
  },
  {
    id: "S-07",
    name: "Kunal Sharma",
    email: "kunal.sharma@digixito.com",
    phone: "9354678205",
    grade: "11th",
    membershipId: "-",
    status: "Not a member",
    gender: GENDER_TYPE.MALE,
  },
  {
    id: "S-08",
    name: "Kunal Sharma",
    email: "kunal.sharma@digixito.com",
    phone: "9354678205",
    grade: "12th",
    membershipId: "M-08",
    status: "Member",
    gender: GENDER_TYPE.MALE,
  },
  {
    id: "S-09",
    name: "Kunal Sharma",
    email: "kunal.sharma@digixito.com",
    phone: "9354678205",
    grade: "10th",
    membershipId: "M-09",
    status: "Member",
    gender: GENDER_TYPE.FEMALE,
  },
  {
    id: "S-10",
    name: "Kunal Sharma",
    email: "kunal.sharma@digixito.com",
    phone: "9354678205",
    grade: "12th",
    membershipId: "-",
    status: "Not a member",
    gender: GENDER_TYPE.FEMALE,
  },
];

export const MEMBER_TYPE = [
  MEMBER_TYPES.NEW_MEMBER,
  MEMBER_TYPES.EXISTING_MEMBER,
];

export const TEACHER_HEADER = [
  "Id",
  "Full Name",

  "Phone",
  "Subject",
  // "Gender",
  "Status",
  "Membership Id",
  "Actions",
];

export const INNOVATION_HEADER = [
  "Id",
  "Title",
  "Category",
  "Status",
  "Actions",
];

export const INNOVATION_DATA = [
  {
    id: "I-001",
    title: "Innovation 1",
    category: "Category 1",
    status: USER_STATUS.ACTIVE,
  },
  {
    id: "I-002",
    title: "Innovation 2",
    category: "Category 2",
    status: USER_STATUS.ACTIVE,
  },
  {
    id: "I-003",
    title: "Innovation 3",
    category: "Category 3",
    status: USER_STATUS.ACTIVE,
  },
  {
    id: "I-004",
    title: "Innovation 4",
    category: "Category 4",
    status: USER_STATUS.ACTIVE,
  },
  {
    id: "I-005",
    title: "Innovation 5",
    category: "Category 5",
    status: USER_STATUS.ACTIVE,
  },
  {
    id: "I-006",
    title: "Innovation 6",
    category: "Category 6",
    status: USER_STATUS.ACTIVE,
  },
  {
    id: "I-007",
    title: "Innovation 7",
    category: "Category 7",
    status: USER_STATUS.ACTIVE,
  },
  {
    id: "I-008",
    title: "Innovation 8",
    category: "Category 8",
    status: USER_STATUS.ACTIVE,
  },
  {
    id: "I-009",
    title: "Innovation 9",
    category: "Category 9",
    status: USER_STATUS.ACTIVE,
  },
  {
    id: "I-010",
    title: "Innovation 10",
    category: "Category 10",
    status: USER_STATUS.ACTIVE,
  },
];

export const RESEARCH_HEADER = [
  "Id",
  "Research Title",
  "Topic",
  "Submitted Date",
  "Status",
  "Actions",
];

export const RESEARCH_DATA = [
  {
    id: "R-001",
    title: "Impact of AI on Primary Education",
    topic: "AI in Education",
    date: "Sep 20, 2023",
    status: USER_STATUS.ACTIVE,
  },
  {
    id: "R-002",
    title: "Renewable Energy in School Curriculums",
    topic: "Sustainability",
    date: "Jan 10, 2024",
    status: USER_STATUS.PENDING,
  },
  {
    id: "R-003",
    title: "Mental Health Strategies for Students",
    topic: "Student Well-being",
    date: "Feb 15, 2024",
    status: USER_STATUS.ACTIVE,
  },
  {
    id: "R-004",
    title: "STEM Education in Rural Areas",
    topic: "STEM",
    date: "Mar 05, 2024",
    status: "Not a member",
  },
  {
    id: "R-005",
    title: "Digital Literacy: A New Core Skill",
    topic: "Digital Education",
    date: "Apr 12, 2024",
    status: USER_STATUS.ACTIVE,
  },
];

export const BOARDS = ["CBSE", "ICSE", "State Board", "IB", "IGCSE"];

export const SCHOOLS = [
  "St. Xavier's International",
  "Greenwood High",
  "The Delhi Public School",
  "Oakridge International",
  "Global Indian School",
];

interface CountryType {
  code: string;
  label: string;
  phone: string;
  suggested?: boolean;
}
export const COUNTRIES: readonly CountryType[] = [
  // { code: "AD", label: "Andorra", phone: "376" },
  // {
  //   code: "AE",
  //   label: "United Arab Emirates",
  //   phone: "971",
  // },
  // { code: "AF", label: "Afghanistan", phone: "93" },
  // {
  //   code: "AG",
  //   label: "Antigua and Barbuda",
  //   phone: "1-268",
  // },
  // { code: "AI", label: "Anguilla", phone: "1-264" },
  // { code: "AL", label: "Albania", phone: "355" },
  // { code: "AM", label: "Armenia", phone: "374" },
  // { code: "AO", label: "Angola", phone: "244" },
  // { code: "AQ", label: "Antarctica", phone: "672" },
  // { code: "AR", label: "Argentina", phone: "54" },
  // { code: "AS", label: "American Samoa", phone: "1-684" },
  // { code: "AT", label: "Austria", phone: "43" },
  // {
  //   code: "AU",
  //   label: "Australia",
  //   phone: "61",
  //   suggested: true,
  // },
  // { code: "AW", label: "Aruba", phone: "297" },
  // { code: "AX", label: "Alland Islands", phone: "358" },
  // { code: "AZ", label: "Azerbaijan", phone: "994" },
  // {
  //   code: "BA",
  //   label: "Bosnia and Herzegovina",
  //   phone: "387",
  // },
  // { code: "BB", label: "Barbados", phone: "1-246" },
  // { code: "BD", label: "Bangladesh", phone: "880" },
  // { code: "BE", label: "Belgium", phone: "32" },
  // { code: "BF", label: "Burkina Faso", phone: "226" },
  // { code: "BG", label: "Bulgaria", phone: "359" },
  // { code: "BH", label: "Bahrain", phone: "973" },
  // { code: "BI", label: "Burundi", phone: "257" },
  // { code: "BJ", label: "Benin", phone: "229" },
  // { code: "BL", label: "Saint Barthelemy", phone: "590" },
  // { code: "BM", label: "Bermuda", phone: "1-441" },
  // { code: "BN", label: "Brunei Darussalam", phone: "673" },
  // { code: "BO", label: "Bolivia", phone: "591" },
  // { code: "BR", label: "Brazil", phone: "55" },
  // { code: "BS", label: "Bahamas", phone: "1-242" },
  // { code: "BT", label: "Bhutan", phone: "975" },
  // { code: "BV", label: "Bouvet Island", phone: "47" },
  // { code: "BW", label: "Botswana", phone: "267" },
  // { code: "BY", label: "Belarus", phone: "375" },
  // { code: "BZ", label: "Belize", phone: "501" },
  // {
  //   code: "CA",
  //   label: "Canada",
  //   phone: "1",
  //   suggested: true,
  // },
  // {
  //   code: "CC",
  //   label: "Cocos (Keeling) Islands",
  //   phone: "61",
  // },
  // {
  //   code: "CD",
  //   label: "Congo, Democratic Republic of the",
  //   phone: "243",
  // },
  // {
  //   code: "CF",
  //   label: "Central African Republic",
  //   phone: "236",
  // },
  // {
  //   code: "CG",
  //   label: "Congo, Republic of the",
  //   phone: "242",
  // },
  // { code: "CH", label: "Switzerland", phone: "41" },
  // { code: "CI", label: "Cote d'Ivoire", phone: "225" },
  // { code: "CK", label: "Cook Islands", phone: "682" },
  // { code: "CL", label: "Chile", phone: "56" },
  // { code: "CM", label: "Cameroon", phone: "237" },
  // { code: "CN", label: "China", phone: "86" },
  // { code: "CO", label: "Colombia", phone: "57" },
  // { code: "CR", label: "Costa Rica", phone: "506" },
  // { code: "CU", label: "Cuba", phone: "53" },
  // { code: "CV", label: "Cape Verde", phone: "238" },
  // { code: "CW", label: "Curacao", phone: "599" },
  // { code: "CX", label: "Christmas Island", phone: "61" },
  // { code: "CY", label: "Cyprus", phone: "357" },
  // { code: "CZ", label: "Czech Republic", phone: "420" },
  // {
  //   code: "DE",
  //   label: "Germany",
  //   phone: "49",
  //   suggested: true,
  // },
  // { code: "DJ", label: "Djibouti", phone: "253" },
  // { code: "DK", label: "Denmark", phone: "45" },
  // { code: "DM", label: "Dominica", phone: "1-767" },
  // {
  //   code: "DO",
  //   label: "Dominican Republic",
  //   phone: "1-809",
  // },
  // { code: "DZ", label: "Algeria", phone: "213" },
  // { code: "EC", label: "Ecuador", phone: "593" },
  // { code: "EE", label: "Estonia", phone: "372" },
  // { code: "EG", label: "Egypt", phone: "20" },
  // { code: "EH", label: "Western Sahara", phone: "212" },
  // { code: "ER", label: "Eritrea", phone: "291" },
  // { code: "ES", label: "Spain", phone: "34" },
  // { code: "ET", label: "Ethiopia", phone: "251" },
  // { code: "FI", label: "Finland", phone: "358" },
  // { code: "FJ", label: "Fiji", phone: "679" },
  // {
  //   code: "FK",
  //   label: "Falkland Islands (Malvinas)",
  //   phone: "500",
  // },
  // {
  //   code: "FM",
  //   label: "Micronesia, Federated States of",
  //   phone: "691",
  // },
  // { code: "FO", label: "Faroe Islands", phone: "298" },
  // {
  //   code: "FR",
  //   label: "France",
  //   phone: "33",
  //   suggested: true,
  // },
  // { code: "GA", label: "Gabon", phone: "241" },
  // { code: "GB", label: "United Kingdom", phone: "44" },
  // { code: "GD", label: "Grenada", phone: "1-473" },
  // { code: "GE", label: "Georgia", phone: "995" },
  // { code: "GF", label: "French Guiana", phone: "594" },
  // { code: "GG", label: "Guernsey", phone: "44" },
  // { code: "GH", label: "Ghana", phone: "233" },
  // { code: "GI", label: "Gibraltar", phone: "350" },
  // { code: "GL", label: "Greenland", phone: "299" },
  // { code: "GM", label: "Gambia", phone: "220" },
  // { code: "GN", label: "Guinea", phone: "224" },
  // { code: "GP", label: "Guadeloupe", phone: "590" },
  // { code: "GQ", label: "Equatorial Guinea", phone: "240" },
  // { code: "GR", label: "Greece", phone: "30" },
  // {
  //   code: "GS",
  //   label: "South Georgia and the South Sandwich Islands",
  //   phone: "500",
  // },
  // { code: "GT", label: "Guatemala", phone: "502" },
  // { code: "GU", label: "Guam", phone: "1-671" },
  // { code: "GW", label: "Guinea-Bissau", phone: "245" },
  // { code: "GY", label: "Guyana", phone: "592" },
  // { code: "HK", label: "Hong Kong", phone: "852" },
  // {
  //   code: "HM",
  //   label: "Heard Island and McDonald Islands",
  //   phone: "672",
  // },
  // { code: "HN", label: "Honduras", phone: "504" },
  // { code: "HR", label: "Croatia", phone: "385" },
  // { code: "HT", label: "Haiti", phone: "509" },
  // { code: "HU", label: "Hungary", phone: "36" },
  // { code: "ID", label: "Indonesia", phone: "62" },
  // { code: "IE", label: "Ireland", phone: "353" },
  // { code: "IL", label: "Israel", phone: "972" },
  // { code: "IM", label: "Isle of Man", phone: "44" },
  { code: "IN", label: "India", phone: "91" },
  // {
  //   code: "IO",
  //   label: "British Indian Ocean Territory",
  //   phone: "246",
  // },
  // { code: "IQ", label: "Iraq", phone: "964" },
  // {
  //   code: "IR",
  //   label: "Iran, Islamic Republic of",
  //   phone: "98",
  // },
  // { code: "IS", label: "Iceland", phone: "354" },
  // { code: "IT", label: "Italy", phone: "39" },
  // { code: "JE", label: "Jersey", phone: "44" },
  // { code: "JM", label: "Jamaica", phone: "1-876" },
  // { code: "JO", label: "Jordan", phone: "962" },
  // {
  //   code: "JP",
  //   label: "Japan",
  //   phone: "81",
  //   suggested: true,
  // },
  // { code: "KE", label: "Kenya", phone: "254" },
  // { code: "KG", label: "Kyrgyzstan", phone: "996" },
  // { code: "KH", label: "Cambodia", phone: "855" },
  // { code: "KI", label: "Kiribati", phone: "686" },
  // { code: "KM", label: "Comoros", phone: "269" },
  // {
  //   code: "KN",
  //   label: "Saint Kitts and Nevis",
  //   phone: "1-869",
  // },
  // {
  //   code: "KP",
  //   label: "Korea, Democratic People's Republic of",
  //   phone: "850",
  // },
  // { code: "KR", label: "Korea, Republic of", phone: "82" },
  // { code: "KW", label: "Kuwait", phone: "965" },
  // { code: "KY", label: "Cayman Islands", phone: "1-345" },
  // { code: "KZ", label: "Kazakhstan", phone: "7" },
  // {
  //   code: "LA",
  //   label: "Lao People's Democratic Republic",
  //   phone: "856",
  // },
  // { code: "LB", label: "Lebanon", phone: "961" },
  // { code: "LC", label: "Saint Lucia", phone: "1-758" },
  // { code: "LI", label: "Liechtenstein", phone: "423" },
  // { code: "LK", label: "Sri Lanka", phone: "94" },
  // { code: "LR", label: "Liberia", phone: "231" },
  // { code: "LS", label: "Lesotho", phone: "266" },
  // { code: "LT", label: "Lithuania", phone: "370" },
  // { code: "LU", label: "Luxembourg", phone: "352" },
  // { code: "LV", label: "Latvia", phone: "371" },
  // { code: "LY", label: "Libya", phone: "218" },
  // { code: "MA", label: "Morocco", phone: "212" },
  // { code: "MC", label: "Monaco", phone: "377" },
  // {
  //   code: "MD",
  //   label: "Moldova, Republic of",
  //   phone: "373",
  // },
  // { code: "ME", label: "Montenegro", phone: "382" },
  // {
  //   code: "MF",
  //   label: "Saint Martin (French part)",
  //   phone: "590",
  // },
  // { code: "MG", label: "Madagascar", phone: "261" },
  // { code: "MH", label: "Marshall Islands", phone: "692" },
  // {
  //   code: "MK",
  //   label: "Macedonia, the Former Yugoslav Republic of",
  //   phone: "389",
  // },
  // { code: "ML", label: "Mali", phone: "223" },
  // { code: "MM", label: "Myanmar", phone: "95" },
  // { code: "MN", label: "Mongolia", phone: "976" },
  // { code: "MO", label: "Macao", phone: "853" },
  // {
  //   code: "MP",
  //   label: "Northern Mariana Islands",
  //   phone: "1-670",
  // },
  // { code: "MQ", label: "Martinique", phone: "596" },
  // { code: "MR", label: "Mauritania", phone: "222" },
  // { code: "MS", label: "Montserrat", phone: "1-664" },
  // { code: "MT", label: "Malta", phone: "356" },
  // { code: "MU", label: "Mauritius", phone: "230" },
  // { code: "MV", label: "Maldives", phone: "960" },
  // { code: "MW", label: "Malawi", phone: "265" },
  // { code: "MX", label: "Mexico", phone: "52" },
  // { code: "MY", label: "Malaysia", phone: "60" },
  // { code: "MZ", label: "Mozambique", phone: "258" },
  // { code: "NA", label: "Namibia", phone: "264" },
  // { code: "NC", label: "New Caledonia", phone: "687" },
  // { code: "NE", label: "Niger", phone: "227" },
  // { code: "NF", label: "Norfolk Island", phone: "672" },
  // { code: "NG", label: "Nigeria", phone: "234" },
  // { code: "NI", label: "Nicaragua", phone: "505" },
  // { code: "NL", label: "Netherlands", phone: "31" },
  // { code: "NO", label: "Norway", phone: "47" },
  // { code: "NP", label: "Nepal", phone: "977" },
  // { code: "NR", label: "Nauru", phone: "674" },
  // { code: "NU", label: "Niue", phone: "683" },
  // { code: "NZ", label: "New Zealand", phone: "64" },
  // { code: "OM", label: "Oman", phone: "968" },
  // { code: "PA", label: "Panama", phone: "507" },
  // { code: "PE", label: "Peru", phone: "51" },
  // { code: "PF", label: "French Polynesia", phone: "689" },
  // { code: "PG", label: "Papua New Guinea", phone: "675" },
  // { code: "PH", label: "Philippines", phone: "63" },
  // { code: "PK", label: "Pakistan", phone: "92" },
  // { code: "PL", label: "Poland", phone: "48" },
  // {
  //   code: "PM",
  //   label: "Saint Pierre and Miquelon",
  //   phone: "508",
  // },
  // { code: "PN", label: "Pitcairn", phone: "870" },
  // { code: "PR", label: "Puerto Rico", phone: "1" },
  // {
  //   code: "PS",
  //   label: "Palestine, State of",
  //   phone: "970",
  // },
  // { code: "PT", label: "Portugal", phone: "351" },
  // { code: "PW", label: "Palau", phone: "680" },
  // { code: "PY", label: "Paraguay", phone: "595" },
  // { code: "QA", label: "Qatar", phone: "974" },
  // { code: "RE", label: "Reunion", phone: "262" },
  // { code: "RO", label: "Romania", phone: "40" },
  // { code: "RS", label: "Serbia", phone: "381" },
  // { code: "RU", label: "Russian Federation", phone: "7" },
  // { code: "RW", label: "Rwanda", phone: "250" },
  // { code: "SA", label: "Saudi Arabia", phone: "966" },
  // { code: "SB", label: "Solomon Islands", phone: "677" },
  // { code: "SC", label: "Seychelles", phone: "248" },
  // { code: "SD", label: "Sudan", phone: "249" },
  // { code: "SE", label: "Sweden", phone: "46" },
  // { code: "SG", label: "Singapore", phone: "65" },
  // { code: "SH", label: "Saint Helena", phone: "290" },
  // { code: "SI", label: "Slovenia", phone: "386" },
  // {
  //   code: "SJ",
  //   label: "Svalbard and Jan Mayen",
  //   phone: "47",
  // },
  // { code: "SK", label: "Slovakia", phone: "421" },
  // { code: "SL", label: "Sierra Leone", phone: "232" },
  // { code: "SM", label: "San Marino", phone: "378" },
  // { code: "SN", label: "Senegal", phone: "221" },
  // { code: "SO", label: "Somalia", phone: "252" },
  // { code: "SR", label: "Suriname", phone: "597" },
  // { code: "SS", label: "South Sudan", phone: "211" },
  // {
  //   code: "ST",
  //   label: "Sao Tome and Principe",
  //   phone: "239",
  // },
  // { code: "SV", label: "El Salvador", phone: "503" },
  // {
  //   code: "SX",
  //   label: "Sint Maarten (Dutch part)",
  //   phone: "1-721",
  // },
  // {
  //   code: "SY",
  //   label: "Syrian Arab Republic",
  //   phone: "963",
  // },
  // { code: "SZ", label: "Swaziland", phone: "268" },
  // {
  //   code: "TC",
  //   label: "Turks and Caicos Islands",
  //   phone: "1-649",
  // },
  // { code: "TD", label: "Chad", phone: "235" },
  // {
  //   code: "TF",
  //   label: "French Southern Territories",
  //   phone: "262",
  // },
  // { code: "TG", label: "Togo", phone: "228" },
  // { code: "TH", label: "Thailand", phone: "66" },
  // { code: "TJ", label: "Tajikistan", phone: "992" },
  // { code: "TK", label: "Tokelau", phone: "690" },
  // { code: "TL", label: "Timor-Leste", phone: "670" },
  // { code: "TM", label: "Turkmenistan", phone: "993" },
  // { code: "TN", label: "Tunisia", phone: "216" },
  // { code: "TO", label: "Tonga", phone: "676" },
  // { code: "TR", label: "Turkey", phone: "90" },
  // {
  //   code: "TT",
  //   label: "Trinidad and Tobago",
  //   phone: "1-868",
  // },
  // { code: "TV", label: "Tuvalu", phone: "688" },
  // {
  //   code: "TW",
  //   label: "Taiwan",
  //   phone: "886",
  // },
  // {
  //   code: "TZ",
  //   label: "United Republic of Tanzania",
  //   phone: "255",
  // },
  // { code: "UA", label: "Ukraine", phone: "380" },
  // { code: "UG", label: "Uganda", phone: "256" },
  {
    code: "US",
    label: "United States",
    phone: "1",
    suggested: true,
  },
  // { code: "UY", label: "Uruguay", phone: "598" },
  // { code: "UZ", label: "Uzbekistan", phone: "998" },
  // {
  //   code: "VA",
  //   label: "Holy See (Vatican City State)",
  //   phone: "379",
  // },
  // {
  //   code: "VC",
  //   label: "Saint Vincent and the Grenadines",
  //   phone: "1-784",
  // },
  // { code: "VE", label: "Venezuela", phone: "58" },
  // {
  //   code: "VG",
  //   label: "British Virgin Islands",
  //   phone: "1-284",
  // },
  // {
  //   code: "VI",
  //   label: "US Virgin Islands",
  //   phone: "1-340",
  // },
  // { code: "VN", label: "Vietnam", phone: "84" },
  // { code: "VU", label: "Vanuatu", phone: "678" },
  // { code: "WF", label: "Wallis and Futuna", phone: "681" },
  // { code: "WS", label: "Samoa", phone: "685" },
  // { code: "XK", label: "Kosovo", phone: "383" },
  // { code: "YE", label: "Yemen", phone: "967" },
  // { code: "YT", label: "Mayotte", phone: "262" },
  // { code: "ZA", label: "South Africa", phone: "27" },
  // { code: "ZM", label: "Zambia", phone: "260" },
  // { code: "ZW", label: "Zimbabwe", phone: "263" },
];

export const US_STATES = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

export const INSTITUTIONS = [
  "Harvard University",
  "Stanford University",
  "MIT",
  "University of Cambridge",
  "University of Oxford",
];

export const TEACHER_STATS_CARD: STATSCARDDATA[] = [
  {
    title: "Total Member Teachers",
    count: "350",
    icon: Groups,
  },
  {
    title: "Total Not a Member Teacher",
    count: "200",
    icon: PersonOff,
  },
  {
    title: "Total Trained Teachers in Innovation",
    count: "150",
    icon: Lightbulb,
  },
  {
    title: "Total Trained Teachers in Research Submissions",
    count: "200",
    icon: Science,
  },
];

export const STUDENT_STATS_CARD: STATSCARDDATA[] = [
  {
    title: "Students Trained On Innovation",
    count: "150",
    icon: Lightbulb,
  },
  {
    title: "Students Trained on Research",
    count: "100",
    icon: Science,
  },
  {
    title: "Students Who Launched Startups",
    count: "20",
    icon: Apartment,
  },
  {
    title: "Students Working as Assistant Mentors",
    count: "50",
    icon: Hail,
  },
];

export const PATENT_STAT_DATA: STATSCARDDATA[] = [
  {
    title: "Total Numbers of Patent Pending",
    count: "20",
    icon: Lightbulb,
  },
  {
    title: "Total Numbers of Patent Granted",
    count: "40",
    icon: FileCopyOutlined,
  },
  {
    title: "Total Numbers of Patent Pending",
    count: "20",
    icon: Lightbulb,
  },
  {
    title: "Total Numbers of Patent Granted",
    count: "40",
    icon: FileCopyOutlined,
  },
];

export const RESEARCH_SUBMISSION_DATA: STATSCARDDATA[] = [
  {
    title: "Totat Numbers Of Research Submitted",
    count: "20",
    icon: FileCopyOutlined,
  },
  {
    title: "Total Numbers Of Research Accepted",
    count: "40",
    icon: FileCopyOutlined,
  },
  {
    title: "Total Numbers Of Research Pending",
    count: "20",
    icon: FileCopyOutlined,
  },
  {
    title: "Total Numbers Of Research Granted",
    count: "40",
    icon: FileCopyOutlined,
  },
];

export const STARTUP_STATS_CARD: STATSCARDDATA[] = [
  {
    title: "Total Number of Startups Launched",
    count: "25",
    icon: RocketLaunch,
  },
  {
    title: "Total Number of Startups Funded",
    count: "10",
    icon: MonetizationOn,
  },
  {
    title: "Total Number of Startups Non-Funded",
    count: "15",
    icon: MoneyOff,
  },
  {
    title: "Total Number of Active Mentorships",
    count: "40",
    icon: BusinessCenter,
  },
];

export const DASHBOARD_STAT_CARDS: STATSCARDPROPS[] = [
  {
    title: "Educators",
    data: TEACHER_STATS_CARD,
  },
  {
    title: "Students",
    data: STUDENT_STATS_CARD,
  },
  {
    title: "Patent",
    data: PATENT_STAT_DATA,
  },
  {
    title: "Research Submission",
    data: RESEARCH_SUBMISSION_DATA,
  },
  {
    title: "Startups",
    data: STARTUP_STATS_CARD,
  },
];

export const CATEGORY_TYPES = ["Innovation", "Research", "Startup"];

export const MODE_TRAINING = [
  {
    label: "Online",
  },
  {
    label: "Offline",
  },
  {
    label: "Hybrid",
  },
];

export const GENDER = [
  GENDER_TYPE.MALE,
  GENDER_TYPE.FEMALE,
  GENDER_TYPE.PREFER_NOT_TO_SAY && "PREFER NOT TO SAY",
];

export const TEAM_LIST_HEADER_DATA: TEAM_LIST_HEADER[] = [
  {
    label: "Id",
  },
  {
    label: "Team Name",
  },
  {
    label: "Mentor Name",
  },
  {
    label: "Assistant Mentor Name",
  },
  {
    label: "Actions",
  },
];

export const TEAM_DATA_TABLE_DATA: TEAM_LIST_DATA_PROPS[] = [
  {
    id: "I01-T01-E01-2026-001",
    teamName: "Team 1",
    mentorName: "Mentor 1",
    assistantMentorName: "Assistant Mentor 1",
  },
  {
    id: "I01-T01-E01-2026-002",
    teamName: "Team 2",
    mentorName: "Mentor 2",
    assistantMentorName: "Assistant Mentor 2",
  },
  {
    id: "I01-T01-E01-2026-003",
    teamName: "Team 3",
    mentorName: "Mentor 3",
    assistantMentorName: "Assistant Mentor 3",
  },
  {
    id: "I01-T01-E01-2026-004",
    teamName: "Team 4",
    mentorName: "Mentor 4",
    assistantMentorName: "Assistant Mentor 4",
  },
  {
    id: "I01-T01-E01-2026-005",
    teamName: "Team 5",
    mentorName: "Mentor 5",
    assistantMentorName: "Assistant Mentor 5",
  },
];
