export enum COLORS {
  WHITE = "#ffffff",
  BLACK = "#000000",
  PRIMARY_NAVY = "#015A50",
  ACCENT_TAN = "#E1E0DA",
  NAVY_GRADIENT_START = "#0B1727",
  NAVY_GRADIENT_END = "#16222F",
  RED = "#C61530",
  BLUE = "#3C6D87",
  PRIMARY_GOLD = "#E1E0DA",
}

export enum USER_ROLES {
  INSTITUTION = "institution",
  EDUCATOR = "mentor",
  STUDENT = "student",
  SCHOOL_ADMIN = "SCHOOL_ADMIN",
  TEACHER = "TEACHER",
  SCHOOL = "SCHOOL",
  EDUCATOR_ADMIN = "EDUCATOR",
}

export enum USER_STATUS {
  ACTIVE = "Active",
  INACTIVE = "Inactive",
  BANNED = "Banned",
  PENDING = "Pending",
}

export enum MEMBER_TYPES {
  NEW_MEMBER = "New Member",
  EXISTING_MEMBER = "Existing Member",
}

export enum GENDER_TYPE {
  MALE = "MALE",
  FEMALE = "FEMALE",
  PREFER_NOT_TO_SAY = "PREFER_NOT_TO_SAY",
}

export enum CURRENCY {
  INR = "INR",
  USD = "USD",
}

export enum BILLING_CYCLE {
  MONTHLY = "MONTHLY",
  YEARLY = "YEARLY",
}

export enum APPROVAL_STATUS {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}

export enum CATEGORY {
  RESEARCH = "RESEARCH",
  INNOVATION = "INNOVATION",
  ENTREPRENEURSHIP = "ENTREPRENEURSHIP",
}

export enum TRAINING_MODE {
  ONLINE = "ONLINE",
  OFFLINE = "OFFLINE",
  HYBRID = "HYBRID",
  ANY_OF_THE_ABOVE = "ANY_OF_THE_ABOVE",
}

export enum TRAINING_NOMINATION_STATUS {
  SELF_NOMINATED = "SELF_NOMINATED",
  SCHOOL_APPROVED = "SCHOOL_APPROVED",
  INTERVIEW_SCHEDULED = "INTERVIEW_SCHEDULED",
  INTERVIEW_COMPLETED = "INTERVIEW_COMPLETED",
  IAIRE_APPROVED = "IAIRE_APPROVED",
  REJECTED = "REJECTED",
  PENDING = "PENDING",
}

export enum PLAN_LIMIT_TYPE {
  MAX_TEACHERS = "MAX_TEACHERS",
  MAX_STUDENTS = "MAX_STUDENTS",
  APPROVE_NOMINEE_TEACHERS = "APPROVE_NOMINEE_TEACHERS",
  MAX_INNOVATION_SUBMISSIONS = "MAX_INNOVATION_SUBMISSIONS",
  MAX_RESEARCH_SUBMISSIONS = "MAX_RESEARCH_SUBMISSIONS",
  MAX_SELF_NOMINATION_TEACHER = "MAX_SELF_NOMINATION_TEACHER",
}
